光辉事迹
VM-Chinese-translate-group/Roguelike-Adventures-and-Dungeons pull request #119
Opened 2023-08-09 06:37 UTC by DC10-10

2023-08-09 08:57 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/13bf2728.snbt
> +	title: "冰与火之歌",
```suggestion
	title: "冰火传说",
```

2023-08-09 09:07 UTC, Wulian233 reviewed
你好

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/2429853f.snbt
> +		"完成任何交易2，500次"
```suggestion
		"完成2500次任意交易"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/34da6d39.snbt
> +	description: "他们吓了你多少次？",
```suggestion
	description: "它们吓了你多少次？",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/352c181e.snbt
> +	description: "我不想杀了你，骨头先生...",
```suggestion
	description: "我其实不想杀你的，骨头先生……",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/3eb6cb56.snbt
> +		title: "共计完成1，000件悬赏",
```suggestion
		title: "共计完成1000件悬赏",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/55ac6e09.snbt
> +		title: "附魔2，500件物品",
```suggestion
		title: "附魔2500件物品",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/718e2266.snbt
> +		"造成1，000，000伤害。"
```suggestion
		"造成一百万伤害。"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/718e2266.snbt
> +		title: "造成1，000，000伤害",
```suggestion
		title: "造成一百万伤害",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/79aafcb5.snbt
> +		title: "捕获100，000只鱼",
```suggestion
		title: "捕获十万只鱼",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/8dc64ead.snbt
> +	description: "你朋友说得对...我最恨她像石头一样",
```suggestion
	description: "你朋友说得对……我最恨她，像石头一样",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/929dee9b.snbt
> +		"吃掉2，500片蛋糕。"
```suggestion
		"吃掉2500片蛋糕。"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/9c0e882f.snbt
> +		"附魔1，000件物品"
```suggestion
		"附魔1000件物品"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/94696e5e.snbt
> +		title: "击杀75鸡蛇",
```suggestion
		title: "击杀75只鸡蛇",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/9c0e882f.snbt
> +		title: "附魔1，000件物品",
```suggestion
		title: "附魔1000件物品",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/9e1253a0.snbt
> +	description: "我喜欢他们的emm...翘臀...以及木乃伊",
```suggestion
	description: "我喜欢他们的emm……翘臀……以及木乃伊",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/9f29c435.snbt
> +		"吃掉1，000片蛋糕"
```suggestion
		"吃掉1000片蛋糕"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/a2b8ed1c.snbt
> +		"造成100，000伤害。"
```suggestion
		"造成十万伤害。"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/b13db796.snbt
> +		"附魔5，000个物品。"
```suggestion
		"附魔5000个物品。"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/b13db796.snbt
> +		title: "附魔5，000个物品",
```suggestion
		title: "附魔5000个物品",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/b3acc0a5.snbt
> +		"捕获50，000只鱼。"
```suggestion
		"捕获50000条鱼。"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/b3acc0a5.snbt
> +		title: "捕获50，000只鱼",
```suggestion
		title: "捕获50000条鱼",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/b7e2242a.snbt
> +	description: "你常常在围着它们转...",
```suggestion
	description: "你常常在围着它们转……",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/c18ad7df.snbt
> +	description: "他们正在敲你的门...",
```suggestion
	description: "它们正在敲你的门……",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/c5e816bf.snbt
> +		title: "击杀1，000只生物",
```suggestion
		title: "击杀1000只生物",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/ca5a03de.snbt
> +		"完成任意1，000次交易"
```suggestion
		"完成任意1000次交易"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/ca5a03de.snbt
> +		title: "完成1，000次交易",
```suggestion
		title: "完成1000次交易",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/d7e5cbb8.snbt
> +		"击杀10，000只生物。"
```suggestion
		"击杀10000只生物。"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/d7e5cbb8.snbt
> +		title: "击杀10，000只生物",
```suggestion
		title: "击杀10000个悚怖尸奴",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/d9d99bcd.snbt
> +	description: "这是一块石头...",
```suggestion
	description: "这是一块石头……",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/dfac9734.snbt
> +		"造成100，000，000伤害。",
```suggestion
		"造成一亿伤害。",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/dfac9734.snbt
> +		title: "造成100，000，000伤害",
```suggestion
		title: "造成一亿伤害",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/edeb3412.snbt
> +	description: "没有蛋糕了。。。还是有？",
```suggestion
	description: "还有没有蛋糕？",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/f7b03758.snbt
> +		title: "完成5，000次交易",
```suggestion
		title: "完成5000次交易",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/f8cb228f.snbt
> +		"捕获1，000只鱼。"
```suggestion
		"捕获1000条鱼。"
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/f8cb228f.snbt
> +		title: "捕获1，000只鱼",
```suggestion
		title: "捕获1000条鱼",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/fb68c6c3.snbt
> +		title: "造成500，000伤害",
```suggestion
		title: "造成500000伤害",
```

2023-08-09 09:07 UTC, Wulian233 commented on config/ftbquests/normal/chapters/693b17a6/fd5bd103.snbt
> +		title: "完成15，000次交易",
```suggestion
		title: "完成15000次交易",
```

2023-08-09 09:09 UTC, Wulian233 reviewed
你好，数字中间不要加逗号。

2023-08-09 09:10 UTC, Wulian233 commented
然后注意动物它和他的区别

2023-08-09 09:11 UTC, Wulian233 commented
然后鱼按条来

2023-08-09 17:07 UTC, DC10-10 commented
OK 下次检查下复制的内容（

2023-08-27 14:10 UTC, nageih requested changes

2023-08-27 14:10 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/003a799d.snbt
> +		"在交错次元的污泥地牢中杀死25只喷火魔兽。"
```suggestion
		"在交错次元的泥沼地牢中杀死25只喷火魔兽。"
```

2023-08-27 14:10 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/446dea27.snbt
> +		"击杀15只九头蛇。"
```suggestion
		"击杀15只暮色森林中的九头蛇。"
```

2023-08-27 14:10 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/718e2266.snbt
> +		"造成100w点伤害。"
```suggestion
		"造成10000000点伤害。"
```

2023-08-27 14:10 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/718e2266.snbt
> +		title: "造成100w点伤害",
```suggestion
		title: "造成1000000点伤害",
```

2023-08-27 14:10 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/79aafcb5.snbt
> +		title: "捕获10w条鱼",
```suggestion
		title: "捕获100000条鱼",
```

2023-08-27 14:10 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/94696e5e.snbt
> +		"击杀75只鸡蛇（冰与火之歌的）"
```suggestion
		"击杀75只鸡蛇（冰火传说的）"
```

2023-08-27 14:10 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/a2b8ed1c.snbt
> +		"造成10w点伤害。"
```suggestion
		"造成100000点伤害。"
```

2023-08-27 14:10 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/a2b8ed1c.snbt
> +		title: "造成10w点伤害",
```suggestion
		title: "造成100000点伤害",
```

2023-09-02 03:16 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/aa061d57.snbt
> +	title: "钓鱼佬II",
```suggestion
	title: "钓鱼佬 II",
```

2023-09-02 03:16 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/b3acc0a5.snbt
> +	title: "钓鱼佬IV",
```suggestion
	title: "钓鱼佬 IV",
```

2023-09-02 03:16 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/bf74e0e2.snbt
> +		"击杀10w只生物。"
```suggestion
		"击杀100000只生物。"
```

2023-09-02 03:16 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/bf74e0e2.snbt
> +		title: "击杀10w只生物",
```suggestion
		title: "击杀100000只生物",
```

2023-09-02 03:16 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/d7b86792.snbt
> +	description: "冥界中最黑暗的阴影变得更加明亮",
```suggestion
	description: "主世界中最黑暗的阴影变得更加明亮",
```

2023-09-02 03:16 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/dfac9734.snbt
> +		"造成一亿点伤害。",
```suggestion
		"造成100000000点伤害。",
```

2023-09-02 03:16 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/dfac9734.snbt
> +		title: "造成一亿点伤害",
```suggestion
		title: "造成100000000点伤害",
```

2023-09-02 03:16 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/f8cb228f.snbt
> +	title: "钓鱼佬I",
```suggestion
	title: "钓鱼佬 I",
```

2023-09-02 03:16 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/fb68c6c3.snbt
> +		"造成50w点伤害。"
```suggestion
		"造成500000点伤害。"
```

2023-09-02 03:16 UTC, nageih commented on config/ftbquests/normal/chapters/693b17a6/fb68c6c3.snbt
> +		title: "造成50w点伤害",
```suggestion
		title: "造成500000点伤害",
```

2023-09-02 03:17 UTC, merged