1.54-ftbq-3e830fd6-独特作物
VM-Chinese-translate-group/Roguelike-Adventures-and-Dungeons pull request #140
Opened 2024-11-07 10:51 UTC by choko-takey

共94个文件的新章节，占坑

2024-11-12 15:40 UTC, choko-takey commented
再见了，所有的1.54（）
记得把多余的任务章节删了

2024-11-12 22:24 UTC, Wulian233 commented
> 再见了，所有的1.54（）
> 记得把多余的任务章节删了

欢迎pr

2024-11-12 22:42 UTC, Wulian233 requested changes
一些关键词、数字间空格、标点用法、断句

2024-11-12 22:42 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/056fc522.snbt
> +		"即使是最隐蔽的作物也逃不过这双眼镜。"
```suggestion
		"即使是最隐蔽的作物也逃不过这双眼睛。"
```

2024-11-12 22:42 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/308b4a0e.snbt
> +		"种植好并右键激活后，它四周的压力板就会以特定序列射出光束。",
```suggestion
		"种植好并右击激活后，它四周的压力板就会以特定序列射出光束。",
```

2024-11-12 22:42 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/432c431e.snbt
> +	description: "看着我我现在是棵植物",
```suggestion
	description: "看着我！我现在是棵植物！",
```

2024-11-12 22:42 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/48172009.snbt
> +		"弄一些秋麒麟捆来让梦想成真。。"
```suggestion
		"弄一些秋麒麟捆来让梦想成真。"
```

2024-11-12 22:42 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/599d7cf8.snbt
> +	description: "另外别叫我 shirley",
```suggestion
	description: "另外别叫我 shirley",
```
待定

2024-11-12 22:42 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/6a56080d.snbt
> +	description: "别担心一点都不疼……应该吧",
```suggestion
	description: "别担心，一点都不疼……应该吧",
```

2024-11-12 22:42 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/81a3b504.snbt
> +		"成熟之后你可以手持物品右键它们来修复物品。"
```suggestion
		"成熟之后你可以手持物品右击它们来修复物品。"
```

2024-11-12 22:42 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/c47e1fc1.snbt
> +		"……每一次……都要！！"
```suggestion
		"每一次……都要！！"
```

2024-11-12 22:42 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/c85afead.snbt
> +		"它们生长度越高所表现出来的贴图质量也越高。"
```suggestion
		"它们生长度越高，所表现出来的贴图质量也越高。"
```

2024-11-12 22:42 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/f6274e1e.snbt
> +		"它看上去很小，不过内部可以储存100格物品，",
```suggestion
		"虽然它看上去很小，不过内部可以储存 100 格物品，",
```

2024-11-13 01:33 UTC, choko-takey commented on config/ftbquests/normal/chapters/3e830fd6/056fc522.snbt
> +		"即使是最隐蔽的作物也逃不过这双眼镜。"
这句话的意思是使用3D眼镜（模组物品）才能观察隐仙子（模组作物），改成这副眼镜吧
```suggestion
		"即使是最隐蔽的作物也逃不过这副眼镜。"
```

2024-11-13 01:38 UTC, choko-takey commented on config/ftbquests/normal/chapters/3e830fd6/599d7cf8.snbt
> +	description: "另外别叫我 shirley",
源自电影《Airplane!》中的台词：
- ”Surely you can't be serious?“ 
- “I am serious — and don’t call me Shirley.”

~~谐音梗翻不了一点（）~~

2024-11-13 10:23 UTC, Wulian233 reviewed
就这样吧

2024-11-13 10:23 UTC, Wulian233 commented on config/ftbquests/normal/chapters/3e830fd6/599d7cf8.snbt
> +	title: "别吵这里很关键",
```suggestion
	title: "你不会是认真的吧",
```

2024-11-13 10:24 UTC, merged