1.55-ftbq-e0575f97-根源魔法
VM-Chinese-translate-group/Roguelike-Adventures-and-Dungeons pull request #145
Opened 2024-11-18 09:23 UTC by choko-takey

共88个文件的重置章节，占坑

2024-11-18 10:31 UTC, Wulian233 commented
重置章节？这里更改的文件都是添加，这是新加入的章节吗？(如果是作者删了又加的重置，需要把旧的任务文件也删除)
(这个pr有亿点点大，我不敢想象)

2024-11-19 09:08 UTC, choko-takey commented
> 重置章节？这里更改的文件都是添加，这是新加入的章节吗？(如果是作者删了又加的重置，需要把旧的任务文件也删除) (这个pr有亿点点大，我不敢想象)

Overhauled roots chapter：指4个任务变成87个任务

2024-11-19 10:14 UTC, Wulian233 commented
好的

2024-11-21 09:19 UTC, choko-takey commented
~~再见了，所有的rad~~
~~作者答应我明年去玩那个游戏6别玩这个游戏1.56好吗（）~~

2024-11-21 10:29 UTC, Wulian233 requested changes

2024-11-21 10:29 UTC, Wulian233 commented on config/ftbquests/normal/chapters/e0575f97/03b9afb0.snbt
> +	description: "Until it is done",
```suggestion
	description: "Until it is done",
```
漏了

2024-11-21 10:29 UTC, Wulian233 commented on config/ftbquests/normal/chapters/e0575f97/154246ce.snbt
> +		"石笋这个名字对某些人来说相当难以念对，这种植物是咒术和仪式所需要的最基本的植物之一。"
题外话啦，我觉得很容易念对啊（）

2024-11-21 10:29 UTC, Wulian233 commented on config/ftbquests/normal/chapters/e0575f97/2a9d60c0.snbt
> +		"使用水泡咒术可以消除部分火焰伤害并免疫岩浆伤害，意味着你终于可以洗个热“熔岩”澡了。"
你可以看一看仓库里有没有出现过其他岩浆错译吗

2024-11-21 10:29 UTC, Wulian233 commented on config/ftbquests/normal/chapters/e0575f97/8e914007.snbt
> +	description: "Rero Rero Rero Rero Rero",
```suggestion
	description: "Rero Rero Rero Rero Rero",
```
漏

2024-11-21 10:29 UTC, Wulian233 commented on config/ftbquests/normal/chapters/e0575f97/8e914007.snbt
> +		"别被骗了，地狱鳞茎并不是糖，而是咒术和仪式所需要的最基本的植物之一。"
地狱还是下界

2024-11-21 12:26 UTC, choko-takey commented on config/ftbquests/normal/chapters/e0575f97/8e914007.snbt
> +	description: "Rero Rero Rero Rero Rero",
罚你去看jojo三回啊三回

2024-11-21 12:26 UTC, choko-takey commented on config/ftbquests/normal/chapters/e0575f97/8e914007.snbt
> +		"别被骗了，地狱鳞茎并不是糖，而是咒术和仪式所需要的最基本的植物之一。"
地狱，这是物品名称

2024-11-21 12:39 UTC, Wulian233 commented on config/ftbquests/normal/chapters/e0575f97/8e914007.snbt
> +	description: "Rero Rero Rero Rero Rero",
那这个就不算了，虽然我觉得很多人也不理解这个

2024-11-21 13:32 UTC, Wulian233 commented
okok，待会合

2024-11-21 13:33 UTC, Wulian233 approved these changes

2024-11-21 13:34 UTC, merged

2024-11-21 13:39 UTC, Wulian233 commented
🌿，@choko-takey 没改https://github.com/VM-Chinese-translate-group/Roguelike-Adventures-and-Dungeons/pull/145#discussion_r1851774066 就合了，你如果有权限直接仓库改把