暮色森林
VM-Chinese-translate-group/Roguelike-Adventures-and-Dungeons pull request #76
Opened 2023-03-13 13:15 UTC by nageih

2023-07-16 09:03 UTC, nageih commented on config/ftbquests/normal/chapters/9dc9f76e/b325bb25.snbt
这个是为了搞贡献用的，不用管

2023-07-16 09:03 UTC, nageih commented on config/ftbquests/normal/chapters/f6bf645c/1b028991.snbt
> +	description: "它其实并不小。。。",
```suggestion
	description: "它其实并不小……",
```

2023-07-16 09:03 UTC, nageih commented on config/ftbquests/normal/chapters/f6bf645c/b2acf8e2.snbt
> +		"伟大的力量带来伟大的。。。喂！注意点！"
```suggestion
		"伟大的力量带来伟大的……喂！注意点！"
```

2023-07-16 09:03 UTC, nageih commented on config/ftbquests/normal/chapters/f6bf645c/b3716d99.snbt
> +		"干得好！这是完成这一章的100金子！"
```suggestion
		"干得好！这是完成这一章的100金币！"
```

2023-07-16 09:03 UTC, nageih commented on config/ftbquests/normal/chapters/f6bf645c/f6c07b06.snbt
> +		"但千万别吃这些豆子。。。",
```suggestion
		"但千万别吃这些豆子……",
```

2023-07-22 05:33 UTC, choko-takey requested changes

2023-07-22 05:33 UTC, choko-takey commented on config/ftbquests/normal/chapters/f6bf645c/12ae72c5.snbt
> +		"遵循这本任务书是在暮色森林中正确的进展。",
```suggestion
		"跟随这条任务线来按正确顺序推动暮色森林的冒险。",
```

2023-07-22 05:33 UTC, choko-takey commented on config/ftbquests/normal/chapters/f6bf645c/7175e718.snbt
> +	description: "迷宫破坏者",
```suggestion
	description: "专拆迷宫",
```

2023-07-22 05:33 UTC, choko-takey commented on config/ftbquests/normal/chapters/f6bf645c/85d0bf37.snbt
> +	title: "杀啊！！！",
```suggestion
	title: "冲刺！！！",
```

2023-07-22 05:33 UTC, choko-takey commented on config/ftbquests/normal/chapters/f6bf645c/9e4d5180.snbt
> +		"在像迷宫的娜迦庭院中杀死一只娜迦。"
```suggestion
		"在迷宫一般的娜迦庭院中杀死一只娜迦。"
```

2023-07-22 05:33 UTC, choko-takey commented on config/ftbquests/normal/chapters/f6bf645c/99878e27.snbt
> +	title: "巫妖在巫妖高塔",
```suggestion
	title: "高塔上的巫妖",
```

2023-07-22 09:16 UTC, choko-takey approved these changes

2023-07-22 12:50 UTC, merged